### ISSUE TITLE
Transcribing Praecatiuncula

### ISSUE THREAD

**Issue by cjmcnamara** [GitClassics/PugnaPorcorum#4]
The last page+ (end of 21 and all of 22) has an extra poem, separate from the Pugna. The meter uses couplets, but I don't think I can use indents without messing up Markdown (?).

**Comment by cjmcnamara** [comment]
In the first line, I can't tell if there's actually a macron (line signifying a long vowel) over that 'e' in prudente or if it's an artifact of the scan. The 'e' is already long by position, so there's no need for a macron, I don't think. I'm inclined to leave it out. Thoughts?

**Comment by swizzard** [comment]
I'm inclined to say it's an artifact--there aren't any other macra.

Re: indentation: https://stackoverflow.com/questions/6046263/how-to-indent-in-a-few-lines-in-markdown-markup (tl;dr: you can't really, but you can fake it in a few different ways, depending on the final presentation)

**Comment by cjmcnamara** [comment]
yeah probably best to avoid indents, thx for the link
